quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerceuser
quarkus.datasource.password=ecommercepass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommercedb

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.hibernate-orm.database.generation=none

quarkus.http.port=8080

mp.messaging.outgoing.order-placed-out.connector=smallrye-kafka
mp.messaging.outgoing.order-placed-out.topic=order-placed
mp.messaging.outgoing.order-placed-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.order-placed-in.connector=smallrye-kafka
mp.messaging.incoming.order-placed-in.topic=order-placed
mp.messaging.incoming.order-placed-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.order-placed-in.auto.offset.reset=earliest

quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200
quarkus.hibernate-search-orm.elasticsearch.protocol=http
quarkus.hibernate-search-orm.schema-management.strategy=create-or-validate
quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy=sync
quarkus.hibernate-search-orm.elasticsearch.version-check.enabled=false

quarkus.infinispan-client.hosts=localhost:11222

mp.jwt.verify.issuer=ecommerce-app

quarkus.hibernate-search-orm.elasticsearch.version=opensearch:2.12

quarkus.infinispan-client.username=admin
quarkus.infinispan-client.password=password
quarkus.infinispan-client.client-intelligence=BASIC

# JWT Security
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ecommerce-backend
smallrye.jwt.sign.key.location=privateKey.pem

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
